#!/sbin/openrc-run

description="Mount modem firmware partition"

MODEM_FW_PARTITION="/dev/mmcblk0p2"
# NOTE: Can't use /dev/disk/by-partlabel symlinks
#       here before udev is started
MNT_POINT="/mnt/firmware-modem"

depend() {
	# We need to mount modem partition before any
	# module is loaded by udev
	before udev
}

start() {
	echo "modem-firmare-mount: starting" > /dev/kmsg
	ebegin "Mounting modem firmware partition..."

	mount -t vfat -o ro "${MODEM_FW_PARTITION}" "${MNT_POINT}"

	eend $?
}
